version: '3'
volumes:
 portainer_data:
services:
 jupyter:
  image: bdp2022/bdp2_review_docker:latest
  ports: 
   - 8888:8888
  environment:
   - GEN_CERT=yes
  volumes:
   - $PWD/work:/home/jovyan/work
 
 portainer:
  image: portainer/portainer
  ports:
    - 9000:9000
  restart: always
  volumes:
   - portainer_data:/data
   - /var/run/docker.sock:/var/run/docker.sock
 redis:
  image: redis:6.2-alpine
  ports:
     - 6379:6379
  command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
